server:
  port: 8082

spring:
  main:
    banner-mode: off
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://130.193.49.157:5432/alfa_battle
    username: alfa_battle
    password: qwe123
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
    generate-ddl: false

  mvc:
    log-request-details: true

  profiles:
    active: local
